---
title: "Exercise5"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Complex Contagion
How do we explain madness/wisdom of crowds? Focusing on individuals inherently gets us 'stuck in the weeds' when trying to explain macro-scale trends. Network analysis allows us to study the connections of people instead of the people themselves.

This helps to explain certain paradoxes (Majority Illusion), like for eg when everyone in a given social network believes that everyone else has more friends than them. This seems possible but is just a consequence of people only being able to see their own part of the network, not the whole. The concept of Majority Illusion could also explain things like group think (eg everyone around me has the same political leanings)

How do we define 'Contagion'? In this instance, it isn't necessarily all negative things like misinformation or madness, it can also be healthy lifestyles, safety information, etc. Contagion is just something that can be quickly spread across a connected network.


## Information Spread
Information cascade: spreading of madness or other nefarious information through a network. The issue with information cascade is its assumption that exposure to an idea once will gaurantee that the exposed node now also believes that idea. Instead we define 'Complex Contagion': The relative % of connected nodes to the node of interest will determine whether or not that node will inherit the idea/belief/contagion. It is not a simple guaranteed-to-spread model, but takes into account the presence of an idea throughout a network and the individual susceptibility of each node.

This works as one might expect generally: having more connections makes one more susceptible to the spread of contagion, but it also works conversely: having many connections to people who do not believe a certain fact can make it impossible for the node to inherit that belief since the majority of their network does not believe it.


## Social Capitol
Having too many connections can lead to a group think situation wherein a network that is too closely knit will become impervious to new/challenging ideas, even if those ideas are correct/vital to safety. Eg Challenger disaster. 

Obviously there is a sweet spot somewhere between too many connections and too few. The number of connections within a group is defined as that group's bonding social capitol. The number of connections between distinct groups is defined as that network's bridging social capitol. 

Networks which contain the right mixture of bonding and bridging social capitol are known as 'small world' networks due to the ease with which contagion/wisdom can spread throughout. 

## Final definitions
Contagions: In the same way that neurons pass signals to the brain, people pass beliefs and behaviors in a society.

Connections: Too few or too many make ideas hard to spread. A 'sweet-spot' mixture is what allows contagions to spread and manifest in a network. 
